#!/usr/bin/env python3

# Release codename poll generator – works with Matterpoll
#
# After each release, increment version and remove the just-used codename from
# candidate_names in this script so that it will not appear in the next
# release's poll.

product="Horizon"
version="31.0.5"
criterion="kind of cookie"

candidate_names = [
    "Aachener Printen",
    "Abernethy",
    "Acıbadem kurabiyesi",
    "Afghan biscuits",
    "Alfajor",
    "Almond biscuit",
    "Almond cake",
    "Amaretti di Saronno",
    "Animal cracker",
    "ANZAC biscuit",
    "New Zealand",
    "Aparon",
    "Apas",
    "Apple cider cookie",
    "Baci di dama",
    "Barquillo",
    "Barquiron",
    "Basler Läckerli",
    "Leckerli",
    "Bath Oliver",
    "Berger Cookie",
    "Berner Haselnusslebkuchen",
    "Berner Honiglebkuchen",
    "Biscocho",
    "Biscuit",
    "Biscuit roll",
    "Bizcochito",
    "Black and white cookie",
    "Half-Moon cookie",
    "Boortsog",
    "Bourbon biscuit",
    "Bourbon cream",
    "Bredela",
    "Broas",
    "Butter cookie",
    "Butter pecan",
    "Camachile cookie",
    "Caramel shortbread",
    "Millionaire's Shortbread",
    "Carrot cake cookie",
    "Cat's tongue cookie",
    "Cavallucci",
    "Caycay",
    "Charcoal biscuit",
    "Chocolate chip cookie",
    "Chocolate-coated marshmallow treats",
    "Chocolate Teacake",
    "Christmas cookies",
    "Cuchuflís",
    "Coconut macaroon",
    "Cornish fairings",
    "Coyotas",
    "Cream cracker",
    "Cuccidati",
    "Custard cream",
    "Digestive biscuit",
    "Drabbelkoek",
    "Dutch letter",
    "Empire biscuit",
    "Fig bar / Fig roll",
    "Finskepinner",
    "Florentine Biscuit",
    "Flour kurabiye",
    "Fortune cookie",
    "Fudge cookie",
    "Galletas de bato",
    "Galletas de patatas",
    "Galletas del Carmen",
    "Galletas pesquera",
    "Garibaldi biscuit",
    "Gazelle ankles",
    "Ghorabiye",
    "Ghoriba",
    "Gingerbread",
    "Gingerbread man",
    "Ginger snaps",
    "Half-moon cookie",
    "Hamantash",
    "Jacobina",
    "Jammie Dodgers",
    "Joe Frogger",
    "Jodenkoek",
    "Jumble",
    "Kaasstengels",
    "Khapse",
    "Kichel",
    "Kleicha",
    "Koulourakia",
    "Kourabiedes",
    "Krumiri",
    "Krumkake",
    "Kue gapit",
    "Kue satu",
    "Lady Finger",
    "Lebkuchen",
    "Lengua de gato",
    "Lincoln biscuit",
    "Linga",
    "Ma'amoul",
    "Macaroon",
    "Macaron",
    "Mamón tostado",
    "Mandelbrot",
    "Maple leaf cream cookies",
    "Marie biscuit",
    "Masa podrida",
    "Moravian spice cookies",
    "Nice biscuit",
    "Nocciolini di Canzo",
    "Oatmeal raisin",
    "Paciencia",
    "Paborita",
    "Panellets",
    "Paprenjak",
    "Party ring",
    "Peanut butter cookie",
    "Petit-Beurre",
    "Pepernoten",
    "Pignolo",
    "Picnic biscuit",
    "Piñata cookie",
    "Polvorón",
    "Pizzelle",
    "Puto seco",
    "Putri salju",
    "Rainbow cookie",
    "Reshteh Khoshkar",
    "Ricciarelli",
    "Rich tea",
    "Rosca",
    "Rosette",
    "Rosquillo",
    "Rum ball",
    "Russian tea cake",
    "Semprong",
    "Shortbread",
    "Silvana",
    "Snickerdoodle",
    "Speculaas",
    "Springerle",
    "Spritzgebäck",
    "Sugar cookie",
    "Tahini cookie",
    "Tareco",
    "Teiglach",
    "Tirggel",
    "Toruń gingerbread",
    "Ube crinkles",
    "Ugoy-ugoy",
    "Uraró",
    "Vanillekipferl",
    "Wafer",
    "Wibele"
]

poll_string = '/poll "First round: Which {} should be the codename for {} {}? Please vote for exactly one." '.format(criterion, product, version)
for candidate in candidate_names:
    poll_string += '"{}" '.format(candidate)

print(poll_string)
